#!/usr/bin/env python3
"""
scripts/generate-labels.py
Reads design-system/tokens.yaml → writes design-system/labels/the-bench-labels.svg

Output: the-bench wordmark (aubergine on cream) + eight-label ink-legend card.
No bin label (Phase 2+). No zone/mode label (Phase 5+, D-16/D-17).

Dependencies: PyYAML (pip install PyYAML)
Security: yaml.safe_load() only — the unsafe loader is forbidden (prevents
          arbitrary object instantiation from a crafted tokens.yaml, ASVS V5).
"""

import yaml
import pathlib
import xml.dom.minidom
from xml.sax.saxutils import escape as _xml_escape

TOKENS_PATH = pathlib.Path("design-system/tokens.yaml")
OUTPUT_PATH = pathlib.Path("design-system/labels/the-bench-labels.svg")

# Google Fonts import. NOTE: the bare '&' separating the two `family=` params is
# illegal in XML (SVG is XML) and breaks the parser ("EntityRef: expecting ';'").
# It is XML-escaped to &amp; on emit; the XML parser unescapes it back to '&'
# before the CSS @import URL is used, so the fonts still load correctly.
FONT_IMPORT_URL = (
    "https://fonts.googleapis.com/css2?family=Archivo:wght@700"
    "&family=IBM+Plex+Mono:wght@400;700&display=swap"
)


def xesc(value):
    """XML-escape any dynamic text/attribute content emitted into the SVG.

    Escapes &, <, > (and, for attributes, the quote chars). This prevents any
    token value containing &, <, or > — or the bare '&' in the font URL — from
    producing malformed XML.
    """
    return _xml_escape(str(value), {'"': "&quot;", "'": "&apos;"})

# SVG canvas dimensions
SVG_W = 480
SVG_H = 600

# Wordmark dimensions
WM_H = 110
WM_PADDING_X = 36
WM_PADDING_Y = 70

# Legend layout
LEGEND_TOP = WM_H + 20
SWATCH_W = 218
SWATCH_H = 58
SWATCH_GAP_X = 8
SWATCH_GAP_Y = 8
SWATCH_COLS = 2
LEGEND_LEFT = 12


def load_tokens():
    """Load tokens using yaml.safe_load (never yaml.load)."""
    with open(TOKENS_PATH, encoding="utf-8") as f:
        return yaml.safe_load(f)


def swatch(name, type_data, x, y):
    """Render a single type swatch: bg rect + type name + meaning text.

    All token-derived values are XML-escaped — colors flow into attributes,
    name/meaning into text content — so no token value can break the SVG.
    """
    bg = xesc(type_data["bg"])
    fg = xesc(type_data["on"])
    meaning = xesc(type_data["meaning"])
    name = xesc(name)
    return (
        f'  <g transform="translate({x},{y})">\n'
        f'    <rect width="{SWATCH_W}" height="{SWATCH_H}" fill="{bg}" rx="4"/>\n'
        f'    <text x="10" y="22" class="label-type" fill="{fg}">{name}</text>\n'
        f'    <text x="10" y="42" class="label-meaning" fill="{fg}">{meaning}</text>\n'
        f'  </g>'
    )


def build_svg(tokens):
    """Build the full SVG: wordmark + 8-label ink-legend card."""
    types = tokens["types"]
    roles = tokens["roles"]
    base  = tokens["base"]

    aubergine = xesc(roles["structure"]["hex"])   # probe identity = The Bench
    cream     = xesc(base["paper"]["hex"])
    font_import = xesc(FONT_IMPORT_URL)            # bare '&' → '&amp;' (valid XML)

    # Ink-legend swatches (8 types, 2 columns)
    swatches = []
    for i, (name, data) in enumerate(types.items()):
        col = i % SWATCH_COLS
        row = i // SWATCH_COLS
        x = LEGEND_LEFT + col * (SWATCH_W + SWATCH_GAP_X)
        y = LEGEND_TOP + row * (SWATCH_H + SWATCH_GAP_Y)
        swatches.append(swatch(name, data, x, y))

    swatches_svg = "\n".join(swatches)

    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-labels.py from design-system/tokens.yaml -->
<!-- Open in Inkscape with fonts installed for print-ready PDF export        -->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 {SVG_W} {SVG_H}" width="{SVG_W}" height="{SVG_H}">
  <style>
    @import url('{font_import}');
    .wordmark     {{ font-family: 'Archivo', system-ui, sans-serif;
                    font-weight: 700; font-size: 34px; }}
    .wordmark-sub {{ font-family: 'IBM Plex Mono', 'Courier New', monospace;
                    font-size: 11px; }}
    .label-type   {{ font-family: 'IBM Plex Mono', 'Courier New', monospace;
                    font-size: 13px; font-weight: 700; }}
    .label-meaning {{ font-family: 'IBM Plex Mono', 'Courier New', monospace;
                    font-size: 10px; }}
  </style>

  <!-- Wordmark: the-bench — Probe identity (aubergine on cream) -->
  <rect x="0" y="0" width="{SVG_W}" height="{WM_H}" fill="{aubergine}"/>
  <text x="{WM_PADDING_X}" y="{WM_PADDING_Y}"
        class="wordmark" fill="{cream}">the-bench</text>
  <text x="{WM_PADDING_X}" y="{WM_PADDING_Y + 22}"
        class="wordmark-sub" fill="{cream}">Signal Path — Probe</text>

  <!-- Ink legend: 8-type Signal Path semantic system -->
{swatches_svg}
</svg>'''


def assert_well_formed_xml(path):
    """Parse the written SVG back as XML; hard-fail the build if malformed.

    SVG is XML, so any unescaped '&', '<', or '>' yields an invalid file that a
    browser refuses to render. Parsing it back here makes invalid SVG a non-zero
    build failure instead of a silent regression caught only by a human.
    """
    text = pathlib.Path(path).read_text(encoding="utf-8")
    try:
        xml.dom.minidom.parseString(text)
    except Exception as exc:  # xml.parsers.expat.ExpatError and friends
        raise SystemExit(
            f"ERROR: generated SVG is not well-formed XML ({path}): {exc}"
        )


def main():
    tokens = load_tokens()
    svg = build_svg(tokens)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(svg, encoding="utf-8")
    assert_well_formed_xml(OUTPUT_PATH)
    print(f"Generated: {OUTPUT_PATH} (well-formed XML)")


if __name__ == "__main__":
    main()
